#!/bin/bash -l                                                                                                                      
#$ -q volta.q                                                                                                                       
#$ -l gpu=1 ## adapter selon besoin                                                                                            
#$ -l dgx=1      
#$ -l h_vmem=200G   
#$ -N diffAD_2s                                                                                                
conda activate $WORK/conda-env

python wrapper2s.py --dataset mvtec --seed 2 --output_dir ./results/diffusionad --eval_only
